### ISSUE TITLE
Dupe glitch working on latest version

### ISSUE THREAD

**Issue by Censorr** [Trophonix/TradePlus#95]
https://www.youtube.com/watch?v=IJ7jau2Cvy4

**Comment by Trophonix** [comment]
I just posted an update to fix the dupe glitch on spigot. When you say the
glitch is working on the latest version, are you referring to the new
version I posted to fix the issue? The plug-in should prevent you from
accepting the trade with an item n your cursor. The fix is working in my
test environment

**Comment by Censorr** [comment]
Apologies didn't see the latest release version, this issue can be closed.
